version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.11.amd64
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.5.11.amd64
    container_name: kafka
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  anonymizer:
    container_name: anonymizer
    build: anonymizer
    ports:
      - 8081:8081
    depends_on:
      - kafka

  distributor:
    container_name: distributor
    build: distributor
    ports:
      - 8080:8080
    depends_on:
      - kafka
