server:
  port: 8080
spring:
  application:
    name: distributor
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: myGroup
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update


